import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CEC from '/public/CEC.png'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="bg">
        <div className='section-0 '><h1>David Conrad</h1></div>
        <div className='section-1 '>
          <a href="https://dad-site-next.vercel.app/" target='_Blank'>
            <Image src={CEC} layout="responsive" id="image" alt="Conrad Eye Centers Logo" />
          </a>
        </div>
        <div className='section-2 '>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Est lorem ipsum dolor sit amet consectetur adipiscing elit. Laoreet non curabitur gravida arcu ac tortor dignissim convallis. Nibh praesent tristique magna sit amet purus gravida. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Enim sed faucibus turpis in eu mi bibendum neque egestas. Convallis aenean et tortor at risus viverra adipiscing at. Eget arcu dictum varius duis at consectetur lorem donec massa. Euismod elementum nisi quis eleifend. Dis parturient montes nascetur ridiculus mus. Nunc sed velit dignissim sodales ut eu sem. Massa placerat duis ultricies lacus sed turpis. Scelerisque purus semper eget duis at. Facilisi etiam dignissim diam quis enim lobortis scelerisque. Adipiscing elit ut aliquam purus sit amet.

          In arcu cursus euismod quis viverra nibh cras pulvinar. Libero enim sed faucibus turpis in eu. Sit amet porttitor eget dolor morbi non arcu risus quis. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Dui sapien eget mi proin sed libero enim sed faucibus. Sit amet consectetur adipiscing elit ut. Arcu risus quis varius quam. Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Iaculis nunc sed augue lacus viverra vitae congue. Sed egestas egestas fringilla phasellus faucibus scelerisque. Turpis in eu mi bibendum neque egestas. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Nam libero justo laoreet sit amet cursus sit amet dictum. Orci eu lobortis elementum nibh tellus. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Tristique et egestas quis ipsum. Est lorem ipsum dolor sit. Sit amet nisl purus in mollis nunc sed id semper. Enim diam vulputate ut pharetra sit amet aliquam.

          Quis hendrerit dolor magna eget est lorem ipsum dolor sit. Purus faucibus ornare suspendisse sed nisi lacus. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Netus et malesuada fames ac turpis egestas. Amet commodo nulla facilisi nullam. Eget nunc lobortis mattis aliquam faucibus purus in massa tempor. Ut sem nulla pharetra diam. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Adipiscing at in tellus integer feugiat scelerisque. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Sed egestas egestas fringilla phasellus. Nisl nisi scelerisque eu ultrices vitae auctor eu. At auctor urna nunc id cursus metus. Egestas congue quisque egestas diam in arcu cursus. Nunc lobortis mattis aliquam faucibus purus in massa tempor. Sem viverra aliquet eget sit amet tellus. Auctor eu augue ut lectus arcu bibendum.

          Vitae tempus quam pellentesque nec nam aliquam sem. Turpis egestas pretium aenean pharetra magna. Viverra nibh cras pulvinar mattis nunc sed. Fusce ut placerat orci nulla pellentesque. Molestie at elementum eu facilisis. Ornare massa eget egestas purus viverra accumsan. Enim neque volutpat ac tincidunt vitae semper quis. Aliquam etiam erat velit scelerisque in dictum non consectetur. Pellentesque habitant morbi tristique senectus. Feugiat sed lectus vestibulum mattis ullamcorper.</div>
        <div className='section-3 '></div>
        <div className='section-4 '></div>
      </div>
    </div>
  )
}
